apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  template:
    spec:
      containers:
        - name: podinfo
          env:
            - name: PODINFO_UI_MESSAGE
              value: "West Cluster"
            - name: PODINFO_UI_COLOR
              value: "#A61E4D"

