apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policy-app-east.yaml
  - policy-app-west.yaml
  - policy-replica-guard.yaml
  - placementbinding-app-east.yaml
  - placementbinding-app-west.yaml
  - placementbinding-replica-guard.yaml

