apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-replica-guard
  namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: replica-guard-frontend
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: frontend
                  namespace: frontend
                spec:
                  replicas: 1

