apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/open-cluster-management-policies.yaml

  - clustersets/east.yaml
  - clustersets/west.yaml
  - clustersets/bindings/east-binding.yaml
  - clustersets/bindings/west-binding.yaml

  - placements/placement-all.yaml
  - placements/placement-east.yaml
  - placements/placement-west.yaml

  - policies/baseline
  - policies/apps
  - policies/image-policy
  - policysets/policyset-baseline.yaml
