apiVersion: v1
kind: Service
metadata:
  name: backend-headless
  namespace: backend
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: http
      port: 9898
      targetPort: http

