apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policyset-baseline
  namespace: open-cluster-management-policies
spec:
  policies:
    - policy-baseline-dev
    - policy-baseline-prod

