apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policy-console-banner-east.yaml
  - policy-console-banner-west.yaml
  - placementbinding-console-banner-east.yaml
  - placementbinding-console-banner-west.yaml

