apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policy-baseline-east.yaml
  - policy-baseline-west.yaml
  - placementbinding-baseline-east.yaml
  - placementbinding-baseline-west.yaml
