apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-baseline-dev
  namespace: open-cluster-management-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-aws-dev
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-baseline-dev
