apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: demo-fb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: demo-fb
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nginx
          image: registry.access.redhat.com/ubi9/nginx-124:1
          imagePullPolicy: IfNotPresent
          command: ["/usr/libexec/s2i/run"]
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: site
              mountPath: /opt/app-root/src/index.html
              subPath: index.html
              readOnly: true
            - name: nginx-conf
              mountPath: /opt/app-root/etc/nginx.d/default.conf
              subPath: default.conf
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
        - name: checker
          image: registry.access.redhat.com/ubi9/python-312:1
          imagePullPolicy: IfNotPresent
          env:
            - name: CLUSTER_NAME
              value: "unknown"
            - name: BACKEND_URL
              value: "http://backend.backend.svc:8080/"
          command: ["python", "/opt/checker/checker.py"]
          ports:
            - name: api
              containerPort: 9000
          volumeMounts:
            - name: checker
              mountPath: /opt/checker/checker.py
              subPath: checker.py
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: site
          configMap:
            name: frontend-site
        - name: nginx-conf
          configMap:
            name: frontend-nginx-conf
        - name: checker
          configMap:
            name: frontend-checker
